name: Generate README

concurrency: 
  group: "Generate README"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Update README.md with library statuses
        run: |
          find providers -name 'build.gradle.kts' | while read -r file; do
          lib_name=$(basename "$(dirname "$file")")
          status=$(grep -oP 'status\.set\((Status\.)?\K[^\)]+' "$file")
          
          case $status in
          Status.Working|Working) status_emoji="ðŸŸ¢ OK";;
          Status.Beta|Beta) status_emoji="ðŸ”µ BETA";;
          Status.Maintenance|Maintenance) status_emoji="ðŸŸ¡ MAINTENANCE";;
          Status.Down|Down) status_emoji="ðŸ”´ DOWN";;
          *) status_emoji="â“ UNKNOWN";;
          esac
          
          echo "| $lib_name | $status_emoji |" >> status_table.md
          done
          
          echo -e "| Name          | Status    |\n| :-----------  | :-------  |" | cat - status_table.md > updated_table.md
          
          if grep -q '| Name          | Status    |' README.md; then
          sed -i '/| Name          | Status    |/,$d' README.md
          fi
          
          line="#### List of available providers:"
          if ! grep -Fxq "$line" README.md
          then echo -e "\n$line" >> README.md
          fi
          cat updated_table.md >> README.md
          
          rm status_table.md updated_table.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: update README [skip ci]"
          title: Providers status update